clc;
clear;
close all
% kf=input('Enter the value of frequency sensitvity, kf: ');
% am=1;
% fm=2;
% beta=(kf*am)/fm;
% t=linspace(0,1,500);
% ac=1;
% fc=20;
% sfm=ac*cos(2*pi*fc*t+(beta*sin(2*pi*fm*t)));
% mt=am*cos(2*pi*fm*t);
% ct=ac*cos(2*pi*fc*t);
% subplot(3,1,1);
% plot(t,mt);
% title('Message signal m(t)');
% subplot(3,1,2);
% plot(t,ct);
% title('Carrier signal c(t)');
% subplot(3,1,3);
% plot(t,sfm);
% title('Modulated signal s(t)');
am=1;
fm=2;
t=linspace(0,1,500);
mt=am*cos(2*pi*fm*t);
y=fmmod(mt,20,40,19,0);
subplot(2,1,1);
plot(mt);
subplot(2,1,2);
plot(y);